### ISSUE TITLE
Installing InformationSystem removes functionality from Model Explorer

### ISSUE THREAD

**Issue by dlathrop** [ObeoNetwork/InformationSystem#21]
I have used the update site to install InformationSystem in three different Eclipse installations, and in each case the Model Explorer no longer has certain functionality:
- Project Dependencies no longer appears
- Model files cannot be expanded to show the top-level model element
- context menus no longer show "Viewpoints Selection"
- context menus no longer show "New Representation" (cannot see top-level model element)

I've installed into
- Obeo Designer Community 10.0
- Eclipse Neon.2 Modeling
- Eclipse Oxygen Modeling
All show same results.

My latest attempt:
- Fresh install of Obeo Designer Community 10.0
- Switched to the Sirius perspective
- Created an Ecore Modeling Project and a simple Ecore model (MyModel contains MyClass)
- Verified the above functionality was present and working.
- Help > Install Software
- Added the site Obeo Marketplace (http://marketplace.obeonetwork.com/updates/sirius2.0)
- Installed Information System - Commons, Designs, Models, and Reversers
- Let Eclipse restart
- Confirmed that the above functionality was no longer present.
- Cannot open the .aird file, even using Open With... > Aird Editor. (It will open with Text Editor, but not much use...)
- I did notice a few errors in the Eclipse log (attached).

In previous attempts, I also setup update site for Sirius 5.0.1
 (e.g., http://download.eclipse.org/sirius/updates/releases/5.0.1/oxygen) and installed missing components of Sirius to see if that fixed it. No luck.

[eclipse.log.txt](https://github.com/ObeoNetwork/InformationSystem/files/1246612/eclipse.log.txt)

**Comment by dlathrop** [comment]
Oops. Forgot to include:
Windows 7
Java 8.0_141

attached: Help > ... > Installation Details
[eclipse.config.txt](https://github.com/ObeoNetwork/InformationSystem/files/1246672/eclipse.config.txt)

**Comment by sthibaudeau** [comment]
Hello, 

Information System is available as ready-to-use eclipse packages that you can download from Github. The eclipse marketplace page references an old luna version and is obsolete.

As for now, there are 2 versions : 

- IS 1.6.1 which is based on Obeo Designer 8
- IS 1.7.0 which is based on Obeo Designer 9

I've just released the 1.7 version as a release candidate 1 but it should be stable enough as we use it as a foundation for our clients.

We have not yet migrated to Obeo Designer 10.

The released packages are available on https://github.com/ObeoNetwork/InformationSystem/releases

If you would like to use an update site instead of a ready-to-use package please contact us.

Regards,
Stéphane

**Comment by dlathrop** [comment]
Thanks. That is working for me. I'm going with the IS 1.7.rc1 download.
